MarcosPauloDeOliveiraFelix
luizdepra/hugo-coder pull request #491
Opened 2020-12-08 19:19 UTC by marcospdofelix

### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

Describe what this pull request achieves.

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into the box(es) that apply:

#### General

- [ ] Describe what changes are being made
- [ ] Explain why and how the changes were necessary and implemented respectively
- [ ] Reference issue with `#<ISSUE_NO>` if applicable

#### Resources

- [ ] If you have changed any SCSS code, run `make release` to regenerate all CSS files

#### Contributors

- [ ] Add yourself to `CONTRIBUTORS.md` if you aren't on it already

2020-12-08 19:50 UTC, nekr0z requested changes
What the?

2020-12-08 20:04 UTC, Lucas-dOliveira approved these changes
MarcosPauloDeOliveiraFelix

2020-12-08 20:04 UTC, v0idpwn commented
MarcosPauloDeOliveiraFelix

2020-12-08 20:13 UTC, thiagolopes commented
MarcosPauloDeOliveiraFelix

2020-12-09 10:42 UTC, marcospdofelix commented
I'm learning, I don't know the tools needed to apply the site
can you pass me a step by step? Want to upload a hugo github site?

2020-12-09 17:16 UTC, luizdepra commented
Bem, pelo seu nome me parece que você fala português, então vamos lá.
Vou acabou criando um Pull Request para o projeto desse tema para Hugo, e não é bem isso que você quer. Então vou fechar aqui.

Sobre como fazer isso, está meio fora do escopo das issues desse projeto. Mas dê uma olhada nesse artigo, ou outro similares. Acredito que eles sejam um bom começo.

https://medium.com/responsive-br/publicando-seu-projeto-hugo-no-github-pages-e5a970d462ac

2020-12-09 17:16 UTC, closed without merging

2020-12-09 17:36 UTC, marcospdofelix commented
thank you

On Wed, Dec 9, 2020 at 2:17 PM Luiz F. A. de Prá <notifications@github.com>
wrote:

> Closed #491 <https://github.com/luizdepra/hugo-coder/pull/491>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/luizdepra/hugo-coder/pull/491#event-4091067210>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR5ASEPOBPE5LBCLQY6MI2DST6WJXANCNFSM4USNHICA>
> .
>